### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by Kainichy** [loliMay/PercentageBatteryIcon#1]
Windows 10 Insider 18290下，使用你的百分比图标时，.NET运行库报错。
之前尚未使用Insider系统时，也没有使用过你的百分比图标。
话说GitHub怎么发图片啊。。。难道图片当附件传送？

**Comment by shiqimei** [comment]
github issues 支持 markdown 语法，[可以参考一下这个](https://www.jianshu.com/p/191d1e21f7ed)。

**Comment by Kainichy** [comment]
OK
![Issues1.NETError](https://user-images.githubusercontent.com/44992049/49682711-1ec52180-faf4-11e8-9267-67ac7544eff1.jpg)
Details框中的完整文字如下引用内容，附件里也有:

>See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

>************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at percentage.TrayIcon.timer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


>************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
>百分比电池图标
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.0
    CodeBase: file:///C:/Users/SkyYkb/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/Startup/%E7%99%BE%E5%88%86%E6%AF%94%E7%94%B5%E6%B1%A0%E5%9B%BE%E6%A0%87.exe
----------------------------------------
>System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
>System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
>System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
>System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
>System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
>System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3694.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

>************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

>For example:

><configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

>When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

[Issues1.NETErrorDetails.txt](https://github.com/lolimay/PercentageBatteryIcon/files/2659454/GitHub.txt)

**Comment by Kainichy** [comment]
# 排除Insider版本问题！
在非Insider版本Windows 10 1809 内部版本17763.194下测试过，仍然有此问题。
点击图中Continue之后会再次弹出此弹窗，在中文系统下得到Details框里的文字是这样的:
附件里面依然是框里的信息。

>有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

>************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 percentage.TrayIcon.timer_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


>************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
>百分比电池图标
    程序集版本:1.0.0.0
    Win32 版本:1.3.0
    基本代码:file:///C:/Users/HiteVision-ops/Desktop/%E7%99%BE%E5%88%86%E6%AF%94%E7%94%B5%E6%B1%A0%E5%9B%BE%E6%A0%87.exe
----------------------------------------
>System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
>System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
>System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
>System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
>System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
>System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
>mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
>System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3190.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

>************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

>例如:

><configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

>启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

[Issues1.NETErrorDetailsChinese.txt](https://github.com/lolimay/PercentageBatteryIcon/files/2693676/Github.txt)

**Comment by RealSharkLi** [comment]
Bonjour:

My DELL XPS 9650 also have this problem. it is running the Windows 10 build 1809 (the latest public version), and is having the same problem that the author have with his computer. can you try to tell us what is happening and how we can prevent it from happening and using it?

BTW this is really a nice idea I think microsoft should hire you.

Bien Cordialement,

**Comment by shiqimei** [comment]
Hi, guys! I am so sorry that this project is not maintained anymore. Because I've migrated to Linux system already and did not have the previous build environment.

Sorry again!

**Comment by xumengoliver** [comment]
报错原因是，代码中参数存储在注册表中，加载时候都会读取，没有做异常判断。建议把参数存储在配置文件中，然后给个默认配置

**Comment by Kainichy** [comment]
配置文件放哪里？程序同目录下config.json吗?

**Comment by xumengoliver** [comment]
> 配置文件放哪里？程序同目录下config.json吗?

现在是在注册表 HKEY_CURRENT_USER\Software\BatteryIcon，字段你可以看作者的源码里的类型自己加进去

**Comment by shiqimei** [comment]
抱歉大家，由于个人精力原因，此项目已不再维护。感谢 @yumdouoliver  指出了异常出现的原因，欢迎提 PR :)

**Comment by yumdouoliver** [comment]
> 抱歉大家，由于个人精力原因，此项目已不再维护。感谢 @yumdouoliver 指出了异常出现的原因，欢迎提 PR :)

可能很多人需求你这个小功能。我把你的注册表信息改成同目录配置文件PR一下吧。。。

**Comment by xumengoliver** [comment]
> 抱歉大家，由于个人精力原因，此项目已不再维护。感谢 @yumdouoliver 指出了异常出现的原因，欢迎提 PR :)

其实这小功能蛮实用的。我就是只需要看电量百分比不在乎其他复杂功能的人。PR了一个可运行版本，把你的注册表配置换成本地目录配置文件了

**Comment by wocala** [comment]
> > 抱歉大家，由于个人精力原因，此项目已不再维护。感谢 @yumdouoliver 指出了异常出现的原因，欢迎提 PR :)
> 
> 其实这小功能蛮实用的。我就是只需要看电量百分比不在乎其他复杂功能的人。PR了一个可运行版本，把你的注册表配置换成本地目录配置文件了

小白求问：请问如何使用这个版本？release里没有更新。谢谢~

**Comment by shiqimei** [comment]
@wocala 需要自己 clone 最新的源码编译。

**Comment by Kainichy** [comment]
@oliver 呃，我觉得还是再改一下，不要是同目录下的xml文件吧，因为你会发现如果把xml和exe一起放在Startup目录下面，开机时会打开xml。我想着把xml搞到AppData下面。
@lolimay 待会儿我给你PR一下吧，顺便我编译好，你release一下。

**Comment by Kainichy** [comment]
呢，弄好了，也PR了。
编译好的exe在这里，拿去release吧。
[PercentageBatteryIcon.zip](https://github.com/lolimay/PercentageBatteryIcon/files/3202997/PercentageBatteryIcon.zip)

**Comment by xumengoliver** [comment]
> @oliver 呃，我觉得还是再改一下，不要是同目录下的xml文件吧，因为你会发现如果把xml和exe一起放在Startup目录下面，开机时会打开xml。我想着把xml搞到AppData下面。
> @lolimay 待会儿我给你PR一下吧，顺便我编译好，你release一下。

好的，谢谢提醒。我觉得这东西很好，但是我系统没有windows的，自己没有在用，所以没考虑到自启动问题。

**Comment by wocala** [comment]
> 呢，弄好了，也PR了。
> 编译好的exe在这里，拿去release吧。
> [PercentageBatteryIcon.zip](https://github.com/lolimay/PercentageBatteryIcon/files/3202997/PercentageBatteryIcon.zip)

我试了下，可以正常启动，也可以正常自启动。
点个赞！
